# Generated by Django 3.1.3 on 2020-12-09 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_infogeon_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='infogeon_users',
        ),
        migrations.RemoveField(
            model_name='crud_users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='crud_users',
            name='password',
        ),
    ]
